language: java
before_install:
  - chmod +x mvnw
before_script:
  - echo "Starting build"
  - psql -c "CREATE DATABASE wic_db;" -U postgres
script:
  - mvn clean package
after_script:
  - echo "Script finished"
after_success:
  - echo "Build was successful. $TRAVIS_TEST_RESULT"
  - ls -l $TRAVIS_BUILD_DIR/target
after_failure:
  - echo "Build was failed"
